sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master
    - develop

cache:
  apt: true


# Set the global environment variables
env:
  matrix:
    # These apply to the latest WP version that is available as a Docker image: https://hub.docker.com/_/wordpress/
    - PHP_VERSION=5.6
    - PHP_VERSION=7.1
    - PHP_VERSION=7.2 APIGEN_DOCS=true COVERAGE=true LINT_SCHEMA=true

before_install:
# Updating Docker
# https://docs.travis-ci.com/user/docker#installing-a-newer-docker-version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- docker --version

# Updating docker-compose
# https://docs.travis-ci.com/user/docker#using-docker-compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version

script:
  - ./run-docker-tests.sh wpunit
  - ./run-docker-tests.sh functional
  - ./run-docker-tests.sh acceptance

after_success:
  # Upload coverage to codecov
  - |
    if [[ "${COVERAGE}" == 'true' ]]; then
      bash <(curl -s https://codecov.io/bash)
    fi
  # Install GraphQL Schema Linter
  # Move to the WordPress Install
  # Generate the Static Schema
  # Lint the Schema
  - |
    if [ $LINT_SCHEMA == true ]; then
      npm install -g graphql-schema-linter
      cd $WP_CORE_DIR
      wp graphql generate-static-schema
      cd $WP_CORE_DIR/wp-content/plugins/wp-graphql
      graphql-schema-linter ./schema.graphql
    fi
  # Generate the APIGen Docs
  #  - |
  #    if [ $APIGEN_DOCS == true ]; then
  #      cd $TRAVIS_BUILD_DIR
  #      vendor/bin/apigen generate --source="src" --destination $TRAVIS_BUILD_DIR/apigen
  #    fi

deploy:
  # Deploy the Generated API docs to the wp-graphql-api-docs repo
  - provider: pages
    # This is set in the Travis CI dashboard
    github_token: $APIGEN_GITHUB_TOKEN
    local_dir: $TRAVIS_BUILD_DIR/apigen
    repo: wp-graphql/wp-graphql-api-docs
    target_branch: master
    # Make sure this is true to ensure the files that were built in the previous step are not cleaned up before deploy
    skip_cleanup: true
    on:
      # Probably switch this to master?
      all_branches: develop
      # Only deploy when APIGEN_DOCS are generated
      condition: $APIGEN_DOCS == true
