version: "3"

services:
  main:
    build:
      context: ../../.
      args:
        PHP_VERSION: "${PHP_VERSION:-7.2}"
    image: wpgraphql-tests-cache
    environment:
      DB_SERVE_NAME: 'wpgraphql_test'
      DB_HOST: 'mysql_db'
      DB_USER: 'root'
      DB_PASSWORD: 'testing'
      WP_VERSION: "${WP_VERSION:-4.9.4}"
    volumes:
      - 'wp-graphql:/project'
    entrypoint:
      #[ "./install-wp-tests.sh", "ignored", "root", "testing", "mysql_test", "4.9.4", "true" ]
      #[ "docker-endpoint.codecept.sh", "run", "${TEST_TYPE}", "--env", "docker" ]
      [ "docker-endpoint.codecept.sh", "--version" ]

  #wordpress:
  #  image: "wordpress:${WP_VERSION:-4.9.4}-php${PHP_VERSION:-7.2}-apache"
  #  environment:
  #    WORDPRESS_DB_HOST: 'mysql_db'
  #    WORDPRESS_DB_NAME: 'wpgraphql_test'
  #    WORDPRESS_DB_USER: 'root'
  #    WORDPRESS_DB_PASSWORD: 'testing'
  #  volumes:
  #    - 'wp-graphql:/var/www/html/wp-content/plugins/wp-graphql:ro'

  mysql_db:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
volumes:
  wp-graphql: